config/routes.rb
Rails.application.routes.draw do

  resources :movies
  resources :users
  resources :people
  resources :movies
  resources :writters
  resources :directors
  resources :comments
  resources :actors
  resources :films
  resources :room_users
  resources :rooms

  
    resources :appointments
    resources :patients
    resources :physicians do
      member do
        post :move
      end
    end
  

  
  root 'teams#index'
  resources :players 
  resources :scoreboards
  resources :players do
    member do
      post :move
    end 
  end

  resources :teams do
      resources :players, :controller => "oimages"
  end
  
  

  

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user
      if user.developer?
        can :manage, :all
      else
        cannot :manage, :all
        #start authorization from here.
        
      end
    end
  end
end

app/models/actor.rb
class Actor < ActiveRecord::Base
	has_many :movies , as: :personable
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :commentable, polymorphic: true
end

app/models/customer.rb
class Customer < ActiveRecord::Base
	has_many :orders, inverse_of: :customer
end

app/models/director.rb
class Director < ActiveRecord::Base
	has_one :movie, as: :personable
end

app/models/employee.rb
class Employee < ActiveRecord::Base
	has_many :pictures, as: :imageable
end

app/models/film.rb
class Film < ActiveRecord::Base
	has_many :comments, as: :commentable
end

app/models/folder.rb
class Folder < ActiveRecord::Base
  belongs_to :parent_folder,-> { where isRoot: true }, class_name: Folder  
  has_many :child_folders, class_name: Folder, foreign_key: "parent_folder_id"
  has_many :super_child_folders, class_name: Folder, foreign_key: "child_folder_id"
end

app/models/movie.rb
class Movie < ActiveRecord::Base
  belongs_to :personable, polymorphic: true
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :customer, inverse_of: :orders
end

app/models/patient.rb
class Patient < ActiveRecord::Base
	has_many :appointments
    has_many :physicians, through: :appointments
end

app/models/person.rb
class Person < ActiveRecord::Base
	belongs_to :peopleable, polymorphic: true
end

app/models/physician.rb
class Physician < ActiveRecord::Base
	has_many :appointments
    has_many :patients, through: :appointments
end

app/models/picture.rb
class Picture < ActiveRecord::Base
	 belongs_to :imageable, polymorphic: true
end

app/models/player.rb
class Player < ActiveRecord::Base
	belongs_to :team, :counter_cache => true
	 # scope :transfers, -> { where(team_id: nil) }

	 validates :name, presence: true
end

app/models/product.rb
class Product < ActiveRecord::Base
	has_many :pictures, as: :imageable
end

app/models/role.rb
class Role < ActiveRecord::Base
  ADMIN=1
  NORMAL=2
  INACTIVE=3

  def self.admin; find_by_id(ADMIN); end
  def self.normal; find_by_id(NORMAL); end
  def self.inactive; find_by_id(INACTIVE); end
                
end

app/models/room.rb
class Room < ActiveRecord::Base
	has_many :room_users
    has_many :users, through: :room_users
end

app/models/team.rb
class Team < ActiveRecord::Base
	belongs_to :user
	has_many :players, dependent: :nullify
	has_many :scoreboards

	validates :team_name, presence: true, uniqueness: true
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/models/writter.rb
class Writter < ActiveRecord::Base
	has_one :movie, as: :personable
end

app/controllers/directors_controller.rb
class DirectorsController < ApplicationController
  before_action :set_director, only: [:show, :edit, :update, :destroy]

  # GET /directors
  # GET /directors.json
  def index
    @directors = Director.all
  end

  # GET /directors/1
  # GET /directors/1.json
  def show
  end

  # GET /directors/new
  def new
    @director = Director.new
  end

  # GET /directors/1/edit
  def edit
  end

  # POST /directors
  # POST /directors.json
  def create
    @director = Director.new(director_params)

    respond_to do |format|
      if @director.save
        format.html { redirect_to @director, notice: 'Director was successfully created.' }
        format.json { render :show, status: :created, location: @director }
      else
        format.html { render :new }
        format.json { render json: @director.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /directors/1
  # PATCH/PUT /directors/1.json
  def update
    respond_to do |format|
      if @director.update(director_params)
        format.html { redirect_to @director, notice: 'Director was successfully updated.' }
        format.json { render :show, status: :ok, location: @director }
      else
        format.html { render :edit }
        format.json { render json: @director.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /directors/1
  # DELETE /directors/1.json
  def destroy
    @director.destroy
    respond_to do |format|
      format.html { redirect_to directors_url, notice: 'Director was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_director
      @director = Director.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def director_params
      params.require(:director).permit(:name)
    end
end

app/helpers/directors_helper.rb
module DirectorsHelper
end

app/views/directors/_form.html.erb
<%= form_for(@director) do |f| %>
  <% if @director.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@director.errors.count, "error") %> prohibited this director from being saved:</h2>

      <ul>
      <% @director.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/directors/edit.html.erb
<h1>Editing Director</h1>

<%= render 'form' %>

<%= link_to 'Show', @director %> |
<%= link_to 'Back', directors_path %>

app/views/directors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Directors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @directors.each do |director| %>
      <tr>
        <td><%= director.name %></td>
        <td><%= link_to 'Show', director %></td>
        <td><%= link_to 'Edit', edit_director_path(director) %></td>
        <td><%= link_to 'Destroy', director, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Director', new_director_path %>

app/views/directors/new.html.erb
<h1>New Director</h1>

<%= render 'form' %>

<%= link_to 'Back', directors_path %>

app/views/directors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @director.name %>
</p>

<%= link_to 'Edit', edit_director_path(@director) %> |
<%= link_to 'Back', directors_path %>