config/routes.rb
Rails.application.routes.draw do

  resources :movies
  resources :users
  resources :people
  resources :movies
  resources :writters
  resources :directors
  resources :comments
  resources :actors
  resources :films
  resources :room_users
  resources :rooms

  
    resources :appointments
    resources :patients
    resources :physicians do
      member do
        post :move
      end
    end
  

  
  root 'teams#index'
  resources :players 
  resources :scoreboards
  resources :players do
    member do
      post :move
    end 
  end

  resources :teams do
      resources :players, :controller => "oimages"
  end
  
  

  

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user
      if user.developer?
        can :manage, :all
      else
        cannot :manage, :all
        #start authorization from here.
        
      end
    end
  end
end

app/models/actor.rb
class Actor < ActiveRecord::Base
	has_many :movies , as: :personable
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :commentable, polymorphic: true
end

app/models/customer.rb
class Customer < ActiveRecord::Base
	has_many :orders, inverse_of: :customer
end

app/models/director.rb
class Director < ActiveRecord::Base
	has_one :movie, as: :personable
end

app/models/employee.rb
class Employee < ActiveRecord::Base
	has_many :pictures, as: :imageable
end

app/models/film.rb
class Film < ActiveRecord::Base
	has_many :comments, as: :commentable
end

app/models/folder.rb
class Folder < ActiveRecord::Base
  belongs_to :parent_folder,-> { where isRoot: true }, class_name: Folder  
  has_many :child_folders, class_name: Folder, foreign_key: "parent_folder_id"
  has_many :super_child_folders, class_name: Folder, foreign_key: "child_folder_id"
end

app/models/movie.rb
class Movie < ActiveRecord::Base
  belongs_to :personable, polymorphic: true
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :customer, inverse_of: :orders
end

app/models/patient.rb
class Patient < ActiveRecord::Base
	has_many :appointments
    has_many :physicians, through: :appointments
end

app/models/person.rb
class Person < ActiveRecord::Base
	belongs_to :peopleable, polymorphic: true
end

app/models/physician.rb
class Physician < ActiveRecord::Base
	has_many :appointments
    has_many :patients, through: :appointments
end

app/models/picture.rb
class Picture < ActiveRecord::Base
	 belongs_to :imageable, polymorphic: true
end

app/models/player.rb
class Player < ActiveRecord::Base
	belongs_to :team, :counter_cache => true
	 # scope :transfers, -> { where(team_id: nil) }

	 validates :name, presence: true
end

app/models/product.rb
class Product < ActiveRecord::Base
	has_many :pictures, as: :imageable
end

app/models/role.rb
class Role < ActiveRecord::Base
  ADMIN=1
  NORMAL=2
  INACTIVE=3

  def self.admin; find_by_id(ADMIN); end
  def self.normal; find_by_id(NORMAL); end
  def self.inactive; find_by_id(INACTIVE); end
                
end

app/models/room.rb
class Room < ActiveRecord::Base
	has_many :room_users
    has_many :users, through: :room_users
end

app/models/team.rb
class Team < ActiveRecord::Base
	belongs_to :user
	has_many :players, dependent: :nullify
	has_many :scoreboards

	validates :team_name, presence: true, uniqueness: true
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/models/writter.rb
class Writter < ActiveRecord::Base
	has_one :movie, as: :personable
end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
  before_action :set_film, only: [:show, :edit, :update, :destroy]

  # GET /films
  # GET /films.json
  def index
    @films = Film.all
  end

  # GET /films/1
  # GET /films/1.json
  def show
  end

  # GET /films/new
  def new
    @film = Film.new
  end

  # GET /films/1/edit
  def edit
  end

  # POST /films
  # POST /films.json
  def create
    @film = Film.new(film_params)

    respond_to do |format|
      if @film.save
        format.html { redirect_to @film, notice: 'Film was successfully created.' }
        format.json { render :show, status: :created, location: @film }
      else
        format.html { render :new }
        format.json { render json: @film.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /films/1
  # PATCH/PUT /films/1.json
  def update
    respond_to do |format|
      if @film.update(film_params)
        format.html { redirect_to @film, notice: 'Film was successfully updated.' }
        format.json { render :show, status: :ok, location: @film }
      else
        format.html { render :edit }
        format.json { render json: @film.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /films/1
  # DELETE /films/1.json
  def destroy
    @film.destroy
    respond_to do |format|
      format.html { redirect_to films_url, notice: 'Film was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_film
      @film = Film.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def film_params
      params.require(:film).permit(:name)
    end
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/views/films/_form.html.erb
<%= form_for(@film) do |f| %>
  <% if @film.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@film.errors.count, "error") %> prohibited this film from being saved:</h2>

      <ul>
      <% @film.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/films/edit.html.erb
<h1>Editing Film</h1>

<%= render 'form' %>

<%= link_to 'Show', @film %> |
<%= link_to 'Back', films_path %>

app/views/films/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Films</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @films.each do |film| %>
      <tr>
        <td><%= film.name %></td>
        <td><%= link_to 'Show', film %></td>
        <td><%= link_to 'Edit', edit_film_path(film) %></td>
        <td><%= link_to 'Destroy', film, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Film', new_film_path %>

app/views/films/new.html.erb
<h1>New Film</h1>

<%= render 'form' %>

<%= link_to 'Back', films_path %>

app/views/films/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @film.name %>
</p>

<%= link_to 'Edit', edit_film_path(@film) %> |
<%= link_to 'Back', films_path %>