config/routes.rb
Rails.application.routes.draw do

  resources :movies
  resources :users
  resources :people
  resources :movies
  resources :writters
  resources :directors
  resources :comments
  resources :actors
  resources :films
  resources :room_users
  resources :rooms

  
    resources :appointments
    resources :patients
    resources :physicians do
      member do
        post :move
      end
    end
  

  
  root 'teams#index'
  resources :players 
  resources :scoreboards
  resources :players do
    member do
      post :move
    end 
  end

  resources :teams do
      resources :players, :controller => "oimages"
  end
  
  

  

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user
      if user.developer?
        can :manage, :all
      else
        cannot :manage, :all
        #start authorization from here.
        
      end
    end
  end
end

app/models/actor.rb
class Actor < ActiveRecord::Base
	has_many :movies , as: :personable
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :commentable, polymorphic: true
end

app/models/customer.rb
class Customer < ActiveRecord::Base
	has_many :orders, inverse_of: :customer
end

app/models/director.rb
class Director < ActiveRecord::Base
	has_one :movie, as: :personable
end

app/models/employee.rb
class Employee < ActiveRecord::Base
	has_many :pictures, as: :imageable
end

app/models/film.rb
class Film < ActiveRecord::Base
	has_many :comments, as: :commentable
end

app/models/folder.rb
class Folder < ActiveRecord::Base
  belongs_to :parent_folder,-> { where isRoot: true }, class_name: Folder  
  has_many :child_folders, class_name: Folder, foreign_key: "parent_folder_id"
  has_many :super_child_folders, class_name: Folder, foreign_key: "child_folder_id"
end

app/models/movie.rb
class Movie < ActiveRecord::Base
  belongs_to :personable, polymorphic: true
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :customer, inverse_of: :orders
end

app/models/patient.rb
class Patient < ActiveRecord::Base
	has_many :appointments
    has_many :physicians, through: :appointments
end

app/models/person.rb
class Person < ActiveRecord::Base
	belongs_to :peopleable, polymorphic: true
end

app/models/physician.rb
class Physician < ActiveRecord::Base
	has_many :appointments
    has_many :patients, through: :appointments
end

app/models/picture.rb
class Picture < ActiveRecord::Base
	 belongs_to :imageable, polymorphic: true
end

app/models/player.rb
class Player < ActiveRecord::Base
	belongs_to :team, :counter_cache => true
	 # scope :transfers, -> { where(team_id: nil) }

	 validates :name, presence: true
end

app/models/product.rb
class Product < ActiveRecord::Base
	has_many :pictures, as: :imageable
end

app/models/role.rb
class Role < ActiveRecord::Base
  ADMIN=1
  NORMAL=2
  INACTIVE=3

  def self.admin; find_by_id(ADMIN); end
  def self.normal; find_by_id(NORMAL); end
  def self.inactive; find_by_id(INACTIVE); end
                
end

app/models/room.rb
class Room < ActiveRecord::Base
	has_many :room_users
    has_many :users, through: :room_users
end

app/models/team.rb
class Team < ActiveRecord::Base
	belongs_to :user
	has_many :players, dependent: :nullify
	has_many :scoreboards

	validates :team_name, presence: true, uniqueness: true
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/models/writter.rb
class Writter < ActiveRecord::Base
	has_one :movie, as: :personable
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: [:show, :edit, :update, :destroy]
  # load_and_authorize_resource


  # GET /players
  # GET /players.json
  def index
        @players = Player.all
        render json: @players
  end

  # GET /players/1
  # GET /players/1.json
  def show
    
  end

  def transfers
       @players = Player.where(:team_id => nil)
      render json: @players
  end

  def move
    @player = Player.find(params[:id])
    render json: @player
  end
  
  # GET /players/new
  def new
    @player = Player.new
  end

  # GET /players/1/edit
  def edit
  end

  # POST /players
  # POST /players.json
  def create
    @player = Player.new(player_params)

    respond_to do |format|
      if @player.save
        format.html { redirect_to @player, notice: 'Player was successfully created.' }
        format.json { render :show, status: :created, location: @player }
      else
        format.html { render :new }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /players/1
  # PATCH/PUT /players/1.json
  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to @player, notice: 'Player was successfully updated.' }
        format.json { render :show, status: :ok, location: @player }
      else
        format.html { render :edit }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    @player.destroy
    respond_to do |format|
      format.html { redirect_to players_url, notice: 'Player was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player
      (@player = Player.find(params[:id]))
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def player_params
      params.require(:player).permit(:name, :age, :position, :select_team, :team_id)
    end
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/_form.html.erb
<%= form_for(@player) do |f| %>
  <% if @player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
      <% @player.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.text_field :age %>
  </div>
  <div class="field">
    <%= f.label :position %><br>
    <%= f.text_field :position %>
  </div> 

  <div class="field">
    <%= f.label :Team_id%><br>
    <%= f.collection_select :team_id, Team.all, :id, :team_name, include_blank: true %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/players/edit.html.erb
<h1>Editing Player</h1>

<%= render "form" %>

<%= link_to "Show", @player %> |
<%= link_to "Back", players_path %>

app/views/players/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Players</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th>Position</th>
      <th>Team</th>
      <th colspan="6"></th>
    </tr>
  </thead>

  <tbody>
    <% @players.each do |player| %>
      <tr>
        <td><%= player.name %></td>
        <td><%= player.age %></td>
        <td><%= player.position %></td>
        <td><%= player.team_id %></td>
        <td><%= link_to 'Show', player %></td>
        <td><%= link_to 'Edit', edit_player_path(player) %></td>
        <td><%= link_to 'Delete', player, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    
        
    <% end %>
  </tbody>
</table>
<br><%= link_to 'Add New Players', new_player_path %>

app/views/players/new.html.erb
<h1>New Player</h1>

<%= render 'form' %>

<%= link_to 'Back', players_path %>

app/views/players/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <strong>Name:</strong>
  <%= @player.name %>
</p>
<p>
  <strong>Age:</strong>
  <%= @player.age %>
</p>
<p>
  <strong>Position:</strong>
  <%= @player.position %>
</p>
<p>
  <strong>Team:</strong>
  <%= @player.team_id %>
</p>


<%= link_to 'Edit', edit_player_path(@player) %> |
<%= link_to 'Back', players_path %>

app/views/players/transfer.html.erb
<h1>List of players to be transferred!</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th>Position</th>
      <th>Team</th>
      <th colspan="6"></th>
    </tr>
  </thead>

  <tbody>
    <% @players.each do |player| %>
      <tr>
        <td><%= player.name %></td>
        <td><%= player.age %></td>
        <td><%= player.position %></td>
        <td><%= player.team_id %></td>
        <td><%= link_to 'Show', player %></td>
        <td><%= link_to 'Edit', edit_player_path(player) %></td>
        <td><%= link_to 'Delete', player, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    
        
    <% end %>
  </tbody>
</table>